model:
  channels: 16
  num_blocks: 7
  semantic_classes: 15
  instance_classes: 14
  sem2ins_classes: []
  semantic_only: True
  semantic_weight: [1.0, 1.0, 51.62, 28.36, 1.54, 21.94, 27.58, 44.26, 47.64, 82.59, 97.28, 71.59, 72.71, 13.34, 17.31]
  with_coords: False
  ignore_label: -100
  grouping_cfg:
    score_thr: 0.2
    radius: 0.9
    mean_active: 3
    class_numpoint_mean: [-1., 10408., 58., 124., 1351., 162., 430., 1090., 451., 26., 43.,
                          61., 39., 109., 1239]
    npoint_thr: 0.05  # absolute if class_numpoint == -1, relative if class_numpoint != -1
    ignore_classes: [0]
  instance_voxel_cfg:
    scale: 3
    spatial_shape: 20
  train_cfg:
    max_proposal_num: 200
    pos_iou_thr: 0.5
  test_cfg:
    x4_split: False
    cls_score_thr: 0.001
    mask_score_thr: -0.5
    min_npoint: 100
  fixed_modules: []
  modified_unet:
    ASPP: True
    DICELOSS: True
    ATTN_ASPP : False
    ASPPv2 : False
data:
  train:
    type: 'stpls3d'
    data_root: 'dataset/stpls3d'
    prefix: 'train_50_25'
    suffix: '_inst_nostuff.pth'
    training: True
    repeat: 4
    voxel_cfg:
      scale: 3
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
  test:
    type: 'stpls3d'
    data_root: 'dataset/stpls3d'
    prefix: 'val'
    suffix: '_inst_nostuff.pth'
    training: False
    voxel_cfg:
      scale: 3
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000

dataloader:
  train:
    batch_size: 4
    num_workers: 4
  test:
    batch_size: 1
    num_workers: 1

optimizer:
  type: 'Adam'
  lr: 0.001

save_cfg:
  semantic: True
  offset: False
  instance: False

fp16: False
epochs: 80
step_epoch: 80
save_freq: 4
pretrain: ''
work_dir: ''
