model:
  channels: 16
  num_blocks: 7
  semantic_classes: 15
  instance_classes: 14
  sem2ins_classes: []
  semantic_only: True
  semantic_weight: [1.0, 1.0, 47.08, 23.55, 1.83, 25.09, 31.46, 28.65, 34.63, 60.0, 114.5, 81.06, 49.75, 10.58, 22.37]
  ignore_label: -100
  with_coords: False
  grouping_cfg:
    score_thr: 0.2
    radius: 0.9
    mean_active: 3
    class_numpoint_mean: [-1.0, 3535.0, 27.0, 59.0, 596.0, 76.0, 199.0, 458.0, 203.0, 12.0, 21.0, 30.0, 19.0, 52.0, 421.0]
    npoint_thr: 0.05  # absolute if class_numpoint == -1, relative if class_numpoint != -1
    ignore_classes: [0]
  instance_voxel_cfg:
    scale: 3
    spatial_shape: 20
  train_cfg:
    max_proposal_num: 200
    pos_iou_thr: 0.5
  test_cfg:
    x4_split: True
    cls_score_thr: 0.001
    mask_score_thr: -0.5
    min_npoint: 100
  fixed_modules: []
  modified_unet:
    ASPP: True
    DICELOSS: False
    ATTN_ASPP : False
    ASPPv2 : False
data:
  train:
    type: 'stpls3d'
    data_root: 'dataset/stpls3d'
    prefix: 'train_100_100'
    suffix: '_inst_nostuff.pth'
    training: True
    repeat: 4
    voxel_cfg:
      scale: 3
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000
  test:
    type: 'stpls3d_100'
    data_root: 'dataset/stpls3d'
    prefix: 'val_100'
    suffix: '_inst_nostuff.pth'
    training: False
    voxel_cfg:
      scale: 3
      spatial_shape: [128, 512]
      max_npoint: 250000
      min_npoint: 5000

dataloader:
  train:
    batch_size: 4
    num_workers: 4
  test:
    batch_size: 1
    num_workers: 1

optimizer:
  type: 'Adam'
  lr: 0.004

save_cfg:
  semantic: True
  offset: True
  instance: False

fp16: False
epochs: 20
step_epoch: 100
save_freq: 4
pretrain: ''
work_dir: ''
